name: DeepLearningFramework CI

on:
  push:
    branches:
      - master
      - ci_testing
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt

      - name: Test dl module
        run: python tests/run_tests.py -p .

